name: Sync Notion Notes

on:
  schedule:
    - cron: '*/30 * * * *'  # Runs every 6 hours
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run sync script
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_PAGE_ID: ${{ secrets.NOTION_PAGE_ID }}
        run: python sync_notion.py

      - name: Commit and push changes
        run: |
          git config user.name "dev3z"
          git config user.email "dkp05022003@gmail.com"
          git add README.md
          git commit -m "Sync Notion notes" || echo "No changes to commit"
          git push
